### ISSUE TITLE
Called twice when connecting/disconnecting to a vpn

### ISSUE THREAD

**Issue by Ciao121** [dominictarr/on-change-network#1]
How can this be avoided?

**Comment by dominictarr** [comment]
I don't know - what does the output look like?

**Comment by Ciao121** [comment]
The output I see is just the one I defined in the console log: e.g console.log('wifi changed')
When connecting (or disconnecting) to (or from) a vpn it happens twice.
When connecting (or disconnecting) to (or from) a WIFI network it happens once.
Empirically it seems to me that it fires on a "connecting" event and on a "connected" event.
Maybe the first time is when the vpn os.networkInterface **is created** (it does not exist f the vpn is not connected) and the second time when it's connected... don't know. Investigating.
What I'm trying to do is to fire an event if a network change occurs. But in the above case the event is fired twice.

**Comment by dominictarr** [comment]
how it works is it polls `os.networkInterfaces()` and if it changes then it emits an event. maybe connecting to your VPN changes it twice? like, prehaps it creates a ipv6 address first, then later an ipv4 (or something like that)... You'll have to figure this out because it's probably related to your VPN software...

Maybe you could just have a delay, so it only emits if it hasn't changed in 5 seconds (instead of 1 second) ?

**Comment by Ciao121** [comment]
Yes, the VPN software is changing the interfaces twice. That's was the problem. Thanks!
